# Generated by Django 4.2.7 on 2026-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_subscription_custom_max_screens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_success', 'Paiement réussi'), ('payment_pending', 'Paiement en cours'), ('payment_failed', 'Paiement échoué'), ('subscription_expiring', 'Abonnement expire bientôt'), ('subscription_expired', 'Abonnement expiré'), ('subscription_renewed', 'Abonnement renouvelé')], max_length=50),
        ),
    ]
