# Generated by Django 4.2.7 on 2026-07-07 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_initial', models.CharField(blank=True, max_length=2)),
                ('avatar_color', models.CharField(default='#ff2d55', max_length=7)),
                ('bio', models.TextField(blank=True)),
                ('favorite_count', models.IntegerField(default=0)),
                ('recent_watch_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
