# Generated by Django 4.2.7 on 2026-07-07 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_slug', models.CharField(max_length=255)),
                ('movie_poster', models.URLField(blank=True)),
                ('content_type', models.CharField(choices=[('movie', 'Film'), ('tv', 'Série')], max_length=20)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=255)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Pourcentage de visionnage')),
                ('duration_watched', models.IntegerField(default=0, help_text='Durée visionnée en secondes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
    ]
