# Generated by Django 4.2.7 on 2026-07-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
