# Generated by Django 4.2.7 on 2026-07-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0008_appupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('help', 'Aide'), ('contact', 'Nous contacter'), ('about', "À propos de l'application"), ('account', 'Compte')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(help_text='Contenu détaillé de la page')),
                ('contact_email', models.EmailField(blank=True, help_text='Email de contact pour la page Nous contacter', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Téléphone de contact', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['content_type'],
            },
        ),
    ]
