# Generated by Django 4.2.7 on 2026-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('mpesa', 'M-PESA'), ('paypal', 'PayPal'), ('bank', 'Compte Bancaire'), ('cinetpay', 'CinetPay')], max_length=20),
        ),
    ]
