# Generated by Django 4.2.7 on 2026-09-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0012_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_slug', models.CharField(max_length=255)),
                ('movie_poster', models.URLField(blank=True)),
                ('content_type', models.CharField(choices=[('movie', 'Film'), ('tv', 'Série')], default='movie', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'movie_slug')},
            },
        ),
    ]
