# Generated by Django 4.2.7 on 2026-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0013_mylistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_slug', models.CharField(max_length=255)),
                ('movie_poster', models.URLField(blank=True)),
                ('content_type', models.CharField(choices=[('movie', 'Film'), ('tv', 'Série')], default='movie', max_length=20)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
