# Generated by Django 4.2.7 on 2026-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_max_screens',
            field=models.IntegerField(blank=True, help_text="Nombre d'écrans personnalisé (remplace celui du plan)", null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_screens',
            field=models.IntegerField(default=2, help_text="Nombre d'écrans simultanés autorisés"),
        ),
    ]
